---
- name: Install bond packet
  apt:
    name: ifenslave
    update_cache: yes
    state: present

- name: set up conf
  template:
    src: templates/bond.j2
    dest: /etc/network/interfaces.d/bond
    owner: root
    group: root
    mode: 0644

- name: restart hosts
  reboot:
    reboot_timeout: 3600
